#!/bin/bash
# MeshBBS Installation Script
# Installs MeshBBS to /opt/meshbbs (or custom location)
# Usage: sudo ./install.sh [install_path]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default installation path
INSTALL_PATH="${1:-/opt/meshbbs}"
SERVICE_USER="${MESHBBS_USER:-bbs}"
SERVICE_GROUP="${MESHBBS_GROUP:-bbs}"

echo -e "${GREEN}MeshBBS Installation Script${NC}"
echo "========================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Check if binary exists
if [ ! -f "target/release/meshbbs" ]; then
    echo -e "${RED}Error: Binary not found at target/release/meshbbs${NC}"
    echo "Please run 'cargo build --release' first"
    exit 1
fi

echo -e "${YELLOW}Installation Configuration:${NC}"
echo "  Install path: $INSTALL_PATH"
echo "  Service user: $SERVICE_USER"
echo "  Service group: $SERVICE_GROUP"
echo ""

# Confirm installation
read -p "Continue with installation? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 0
fi

echo ""
echo "Installing MeshBBS..."

# Create service user if it doesn't exist
if ! id "$SERVICE_USER" &>/dev/null; then
    echo -e "${YELLOW}Creating service user: $SERVICE_USER${NC}"
    useradd -r -s /bin/false -d "$INSTALL_PATH" -c "MeshBBS Service User" "$SERVICE_USER"
fi

# Add user to dialout group for serial port access
echo -e "${YELLOW}Adding $SERVICE_USER to dialout group${NC}"
usermod -a -G dialout "$SERVICE_USER" 2>/dev/null || true

# Create installation directory
echo -e "${YELLOW}Creating installation directory: $INSTALL_PATH${NC}"
mkdir -p "$INSTALL_PATH"
mkdir -p "$INSTALL_PATH/data"
mkdir -p "$INSTALL_PATH/data/messages"
mkdir -p "$INSTALL_PATH/data/users"
mkdir -p "$INSTALL_PATH/data/files"
mkdir -p "$INSTALL_PATH/data/tinymush"
mkdir -p "$INSTALL_PATH/data/backups"

# Copy binary
echo -e "${YELLOW}Installing binary${NC}"
cp target/release/meshbbs "$INSTALL_PATH/"
chmod 755 "$INSTALL_PATH/meshbbs"

# Copy or create configuration
if [ ! -f "$INSTALL_PATH/config.toml" ]; then
    echo ""
    echo -e "${GREEN}Configuration Setup${NC}"
    echo "===================="
    echo ""
    
    # Ask for sysop password
    echo -e "${YELLOW}Please set a sysop password (for administrative access)${NC}"
    echo "This password will be hashed and stored securely."
    echo ""
    
    SYSOP_PASSWORD=""
    while [ -z "$SYSOP_PASSWORD" ]; do
        read -s -p "Sysop password (min 8 characters): " SYSOP_PASSWORD
        echo ""
        if [ ${#SYSOP_PASSWORD} -lt 8 ]; then
            echo -e "${RED}Password must be at least 8 characters${NC}"
            SYSOP_PASSWORD=""
            continue
        fi
        read -s -p "Confirm password: " SYSOP_PASSWORD_CONFIRM
        echo ""
        if [ "$SYSOP_PASSWORD" != "$SYSOP_PASSWORD_CONFIRM" ]; then
            echo -e "${RED}Passwords do not match${NC}"
            SYSOP_PASSWORD=""
        fi
    done
    
    # Hash the password using the meshbbs binary
    echo -e "${YELLOW}Hashing password...${NC}"
    SYSOP_HASH=$(echo -n "$SYSOP_PASSWORD" | "$INSTALL_PATH/meshbbs" --hash-password 2>/dev/null || echo "")
    
    if [ -z "$SYSOP_HASH" ]; then
        echo -e "${YELLOW}Warning: Could not hash password automatically. Will use plaintext marker.${NC}"
        echo -e "${YELLOW}You'll need to run: meshbbs --hash-password${NC}"
        SYSOP_HASH="REPLACE_WITH_HASHED_PASSWORD"
    fi
    
    # Ask for serial port
    echo ""
    echo -e "${YELLOW}Select serial port for Meshtastic device:${NC}"
    echo "Common ports:"
    echo "  1) /dev/ttyUSB0 (default)"
    echo "  2) /dev/ttyACM0"
    echo "  3) /dev/ttyUSB1"
    echo "  4) Custom"
    echo ""
    read -p "Select option (1-4) [1]: " SERIAL_CHOICE
    SERIAL_CHOICE=${SERIAL_CHOICE:-1}
    
    case $SERIAL_CHOICE in
        1) SERIAL_PORT="/dev/ttyUSB0" ;;
        2) SERIAL_PORT="/dev/ttyACM0" ;;
        3) SERIAL_PORT="/dev/ttyUSB1" ;;
        4) 
            read -p "Enter custom serial port: " SERIAL_PORT
            ;;
        *) SERIAL_PORT="/dev/ttyUSB0" ;;
    esac
    
    echo -e "${YELLOW}Creating config.toml${NC}"
    
    # Create config file
    cat > "$INSTALL_PATH/config.toml" <<EOF
# MeshBBS Configuration File
# Generated by install script on $(date)

[bbs]
# Display name for your BBS
name = "Your MeshBBS Name"

# Location (shown to users)
location = "90210"

# Description of your BBS
description = "Some information about your MeshBBS"

# Sysop (system operator) username
sysop_name = "sysop"

# Sysop password hash (generated during installation)
sysop_password_hash = "$SYSOP_HASH"

# Allow public login without registration
public_login = false

# Session timeout in minutes
session_timeout_minutes = 30

[meshtastic]
# Serial port for Meshtastic device
serial_port = "$SERIAL_PORT"

# Baud rate (usually 115200)
baud_rate = 115200

[meshtastic.ident]
# Send identification beacon periodically
enabled = true
# Beacon interval in seconds (3600 = 1 hour)
interval_seconds = 3600

[storage]
# Data directory (absolute path)
data_dir = "$INSTALL_PATH/data"

# Maximum message size in bytes
max_message_size = 230

[storage.backup]
# Enable automatic backups
enabled = true
# Backup retention in days
retention_days = 30
# Backup interval in hours
interval_hours = 24

[games]
# Enable TinyHack roguelike game
tinyhack_enabled = true

# Enable TinyMUSH multi-user game
tinymush_enabled = true

[games.tinymush]
# TinyMUSH data directory
data_dir = "$INSTALL_PATH/data/tinymush"

[weather]
# OpenWeatherMap API key - Get one at https://openweathermap.org/api
# IMPORTANT: Replace this with your actual API key!
api_key = "REPLACE_WITH_YOUR_API_KEY"

# Default location for weather (ZIP code or city name)
default_location = "90210"

# Temperature units: "metric" (Celsius) or "imperial" (Fahrenheit)
units = "imperial"

[welcome]
# Welcome message system (greets new nodes on the mesh)
enabled = false

# Welcome via private DM
private_enabled = false
private_template = "Welcome to {bbs_name}! This is a bulletin board system. Send me '^HELP' for commands."

# Welcome via public channel
public_enabled = false
public_template = "📻 New station detected! Welcome to the mesh. Send '^HELP' to learn about this BBS."

# Cooldown between welcomes (minutes)
rate_limit_minutes = 5
EOF
    
    echo -e "${GREEN}Configuration created!${NC}"
    echo ""
    echo "Important: Your sysop password has been hashed and stored securely."
    echo ""
    
else
    echo -e "${YELLOW}Existing config.toml found, not overwriting${NC}"
fi

chmod 644 "$INSTALL_PATH/config.toml" 2>/dev/null || true

# Copy topics example if data/topics.json doesn't exist
if [ ! -f "$INSTALL_PATH/data/topics.json" ]; then
    if [ -f "topics.example.json" ]; then
        echo -e "${YELLOW}Installing topics.json${NC}"
        cp topics.example.json "$INSTALL_PATH/data/topics.json"
    fi
fi

# Set ownership
echo -e "${YELLOW}Setting ownership${NC}"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_PATH"

# Set permissions
chmod 755 "$INSTALL_PATH"
chmod 755 "$INSTALL_PATH/data"
chmod 755 "$INSTALL_PATH/meshbbs"

# Install systemd service if systemd is available
if command -v systemctl &> /dev/null; then
    echo -e "${YELLOW}Installing systemd service${NC}"
    
    # Create service file
    cat > /etc/systemd/system/meshbbs.service <<EOF
[Unit]
Description=MeshBBS - Bulletin Board System for Meshtastic
Documentation=https://martinbogo.github.io/meshbbs/
After=network.target
Wants=network.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_GROUP
WorkingDirectory=$INSTALL_PATH
ExecStart=$INSTALL_PATH/meshbbs
Restart=always
RestartSec=10
TimeoutStopSec=30

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=meshbbs

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$INSTALL_PATH/data $INSTALL_PATH/meshbbs.log
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictRealtime=true
RestrictNamespaces=true

# Environment
Environment="RUST_LOG=info"

# Resource limits
MemoryLimit=512M
TasksMax=100

[Install]
WantedBy=multi-user.target
EOF

    # Reload systemd
    systemctl daemon-reload
    
    echo ""
    echo -e "${GREEN}Systemd service installed!${NC}"
    echo "To enable and start the service:"
    echo "  sudo systemctl enable meshbbs"
    echo "  sudo systemctl start meshbbs"
    echo ""
    echo "To check status:"
    echo "  sudo systemctl status meshbbs"
    echo "  sudo journalctl -u meshbbs -f"
fi

echo ""
echo -e "${GREEN}Installation complete!${NC}"
echo ""
echo "Installation details:"
echo "  Binary:        $INSTALL_PATH/meshbbs"
echo "  Config:        $INSTALL_PATH/config.toml"
echo "  Data:          $INSTALL_PATH/data"
echo "  User:          $SERVICE_USER"
echo ""
echo "Next steps:"
echo "  1. Edit configuration: sudo nano $INSTALL_PATH/config.toml"
echo "  2. Set sysop password in config.toml"
echo "  3. Configure serial port (usually /dev/ttyACM0 or /dev/ttyUSB0)"
if command -v systemctl &> /dev/null; then
    echo "  4. Enable service: sudo systemctl enable meshbbs"
    echo "  5. Start service: sudo systemctl start meshbbs"
else
    echo "  4. Run manually: cd $INSTALL_PATH && sudo -u $SERVICE_USER ./meshbbs"
fi
echo ""
echo "Documentation: $INSTALL_PATH/docs/ or https://martinbogo.github.io/meshbbs/"
echo ""
